Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = false

### Frontend ###
  config.vm.define "maven" do |maven|
    maven.vm.box = "ubuntu/focal64"
    maven.vm.hostname = "maven"
    maven.vm.network "private_network", ip: "192.168.56.133"
    maven.vm.network "forwarded_port", guest: 8080, host: 8080
    maven.vm.synced_folder ".\\vagrant_folder\\", "/vagrant"
    maven.vm.provider "virtualbox" do |vb|
      vb.memory = "4000"
      vb.name = "maven"
    end
    # maven.vm.provision "shell", path: ".\\vagrant_folder\\init.sh"
    # docker01.vm.provision "shell", path: ".\\vagrant_folder\\docker.sh"
  end
end