stacks:
  vars:
    ansible_ssh_private_key_file: /home/vagrant/.ssh/ssh_key.pem
  hosts:
    jenkins:
      ansible_host: 192.168.60.100
    monitor:
      ansible_host: 192.168.60.110
    prod:
      ansible_host: 192.168.60.150