Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-vbguest"]
  config.vm.hostname = "nginx-handbook-box"
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/focal64"

  config.vm.define "nginx-handbook-box"
  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
    vb.name = "nginx-handbook"
  end
  config.vm.synced_folder ".\\vagrant_folder", "/vagrant"
  # config.vm.provision "shell", path: "../lemp.sh" 
  # config.vbguest.auto_update = true
  # config.vbguest.installer_options = { allow_kernel_upgrade: true }
  # config.vbguest.installer_hooks[:before_start] = [
  #   "echo 'vboxsf' > /etc/modules-load.d/vboxsf.conf", 
  #   "systemctl restart systemd-modules-load.service", 
  #   "echo '=== Verifying vboxsf module is loaded'", 
  #   "cat /proc/modules | grep vbox" 
  # ]

end