Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = false

### Frontend ###
  config.vm.define "fe01" do |fe01|
    fe01.vm.box = "ubuntu/focal64"
    fe01.vm.hostname = "fe01"
    fe01.vm.network "private_network", ip: "192.168.56.100"
    fe01.vm.synced_folder ".\\vagrant_folder\\fe01", "/vagrant"
    fe01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "fe01"
    fe01.vm.provision "shell", path: ".\\vagrant_folder\\fe01\\init.sh"
    end
  end
  
### Reverse Proxy ###
  config.vm.define "proxy01" do |proxy01|
    proxy01.vm.box = "ubuntu/focal64"
    proxy01.vm.hostname = "proxy01"
    proxy01.vm.network "private_network", ip: "192.168.56.110"
    proxy01.vm.synced_folder ".\\vagrant_folder\\proxy01", "/vagrant"
    proxy01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "proxy01"
    end
  end
### Customer Service ###
  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.box = "ubuntu/focal64"
    mongodb.vm.hostname = "mongodb"
    mongodb.vm.network "private_network", ip: "192.168.56.150"
    mongodb.vm.synced_folder ".\\vagrant_folder\\mongodb", "/vagrant"
    mongodb.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mongodb"
    end
    mongodb.vm.provision "shell", path: ".\\vagrant_folder\\mongodb\\init.sh"
  end
### Customer Service ###
  config.vm.define "rabbitMQ" do |rabbitMQ|
    rabbitMQ.vm.box = "ubuntu/focal64"
    rabbitMQ.vm.hostname = "rabbitMQ"
    rabbitMQ.vm.network "private_network", ip: "192.168.56.200"
    rabbitMQ.vm.synced_folder ".\\vagrant_folder\\rabbitMQ", "/vagrant"
    rabbitMQ.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "rabbitMQ"
    end
    rabbitMQ.vm.provision "shell", path: ".\\vagrant_folder\\rabbitMQ\\rabbitmq.sh"
  end
### Customer Service ###
  config.vm.define "customer" do |customer|
    customer.vm.box = "ubuntu/focal64"
    customer.vm.hostname = "customer"
    customer.vm.network "private_network", ip: "192.168.56.101"
    customer.vm.synced_folder ".\\vagrant_folder\\customer", "/vagrant"
    customer.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "_customer"
    end
  end
  
### Customer Service ###
  config.vm.define "products" do |products|
    products.vm.box = "ubuntu/focal64"
    products.vm.hostname = "products"
    products.vm.network "private_network", ip: "192.168.56.102"
    products.vm.synced_folder ".\\vagrant_folder\\products", "/vagrant"
    products.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "products"
    end
    products.vm.provision "shell", path: ".\\vagrant_folder\\products\\init.sh"
  end
  
### Customer Service ###
  config.vm.define "shopping" do |shopping|
    shopping.vm.box = "ubuntu/focal64"
    shopping.vm.hostname = "shopping"
    shopping.vm.network "private_network", ip: "192.168.56.103"
    shopping.vm.synced_folder ".\\vagrant_folder\\shopping", "/vagrant"
    shopping.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "shopping"
    end
  end

end