Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = false
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.synced_folder ".\\vagrant_folder", "/vagrant"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "web01"
    end
    web01.disksize.size = "10GB"
  end
  
### tomcat vm ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "geerlingguy/centos7"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.synced_folder ".\\vagrant_folder", "/vagrant"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "app01"
    end
    app01.disksize.size = "10GB"
  end
   
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "geerlingguy/centos7"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
    rmq01.vm.synced_folder ".\\vagrant_folder", "/vagrant"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "rmq01"
    end
    rmq01.disksize.size = "10GB"
  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "geerlingguy/centos7"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.synced_folder ".\\vagrant_folder", "/vagrant"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mc01"
    end
    mc01.disksize.size = "10GB"
  end
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.synced_folder ".\\vagrant_folder", "/vagrant"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "db01"
    end
    db01.disksize.size = "10GB"
  end
end