---
- name: Download Node Exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /etc/node_exporter
    owner: node_exporter
    group: node_exporter
