---
- name: Import variables
  include_vars: ../vars/vars.yaml

- name: Create user
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    shell: node_exporter
    create_home: false

- name: Create folder
  ansible.builtin.file:
    path: /etc/node_exporter
    owner: node_exporter
    group: node_exporter

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_url }}"
    dest: /home/vagrant/node_exporter.tar.gz
    # owner: node_exporter
    # group: node_exporter

# - name: Extract Node Exporter
#   ansible.builtin.unarchive:
#     url: {{ node_exporter_url }}
#     dest: /etc/node_exporter
#     owner: node_exporter
#     group: node_exporter
