---
- name: Import variables
  include_vars: ../vars/vars.yaml

- name: Create group
  become: true
  become_method: sudo
  ansible.builtin.group:
    name: node_exporter
    state: present

- name: Create user
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    shell: /bin/false
    create_home: false

- name: Create folder
  become: true
  become_method: sudo
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: node_exporter
    group: node_exporter
  with_items:
    - /etc/node_exporter/
    - /home/vagrant/node_exporter_file/

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_url }}"
    dest: /home/vagrant/node_exporter.tar.gz
    # owner: node_exporter
    # group: node_exporter

- name: Extract Node Exporter
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/vagrant/node_exporter.tar.gz
    dest: /home/vagrant/node_exporter_file/
  register: node_exporter_unarchive

- name: Remove tar file
  ansible.builtin.file:
    path: /home/vagrant/node_exporter.tar.gz
    state: absent
  when: node_exporter_unarchive.changed

- name: Move Node Exporter to /usr/lib
  become: true
  ansible.builtin.shell: 
    cmd: sudo cp /home/vagrant/node_exporter_file/node_exporter*/node_exporter /usr/bin/node_exporter
  args:
    executable: /bin/bash

- name: Change node_exporter ownership
  become: true
  ansible.builtin.file:
    path: /usr/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    state: file

- name: Create Node Service
  become: true
  ansible.builtin.template:
    src: node_exporter.service
    dest: /usr/lib/systemd/system/node_exporter.service
    mode: '0664'
    owner: node_exporter
    group: node_exporter

- name: Reload daemon
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    daemon_reload: yes
    state: reloaded
  notify: 
    - Start Node Exporter
    - Enable Node Exporter
