Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = false

### Frontend ###
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.133"
    jenkins.vm.synced_folder ".\\vagrant_folder\\", "/vagrant"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "4000"
      vb.name = "jenkins"
    end
    jenkins.vm.provision "shell", path: ".\\vagrant_folder\\init.sh"
    # docker01.vm.provision "shell", path: ".\\vagrant_folder\\docker.sh"

  end
end